print(type(5))
print(type(2.5))
print(type('hello'))
print(type(1+3j))
print(type([1, 2, 3]))
print(type({'a': 1, "b": True}))
print(type(True))
print(type((1, 2, False)))
print(5/2)
print(1*2)
print(5-2)
print(5**2)
print(5//2)
print(5 % 2)
print(5+2)
