s = "Thirty"+"Days"+"Of"+"Python"
s1 = "Coding"+"For"+"All"
company = "Coding For All"
print(company)
print(len(company))
print(company.upper())
print(company.lower())
print(company.capitalize())
print(company.title())
print(company.swapcase())
print(company[:6])
print(company.index("Coding"))
print(company.replace("Coding", "Python"))
print(company.replace("Everyone", "All"))
print(company.split(" "))
print("Facebook, Google, Microsoft, Apple, IBM, Oracle, Amazon".split(","))
print(company[0])
print(len(company)-1)
print(company[10])
s2 = 'Python For Everyone'
s3 = "Coding For All"
print(s3.find("C"))
print(s3.find("F"))
print(s3.rfind("l"))
print('You cannot end a sentence with because because because is a conjunction'.find("because"))
print("You cannot end a sentence with because because because is a conjunction".rfind("because"))
print("You cannot end a sentence with because because because is a conjunction".replace(
    "because because because", ""))
print(company.startswith("Coding"))
print(company.endswith("coding"))
print('   Coding For All      '.strip())
print("30DaysOfPython".isidentifier())
print("thirty_days_of_python".isidentifier())
print("#".join(['Django', 'Flask', 'Bottle', 'Pyramid', 'Falcon']))
print("I am enjoying this challenge.\nI just wonder what is next.")
print("Name\tAge\tCountry\tCity\nRajveer\t18\tINDIA\tRajkot")
print("radius is {}\narea = {} * radius ** {}\nThe area of a circle with radius {} is {} meters square".format(10, 3.14, 2, 10, 314))
print("{} + {} ={}".format(8, 6, 14))
print("{} - {} ={}".format(8, 6, 8-6))
print("{} * {} ={}".format(8, 6, 8*6))
print("{} / {} ={:.2f}".format(8, 6, 8/6))
print("{} % {} ={}".format(8, 6, 8 % 6))
print("{} // {} ={}".format(8, 6, 8//6))
print("{} ** {} ={}".format(8, 6, 8**6))
